export const NICHES = [
  'Medicina',
  'Saúde',
  'Construção/Engenharia',
  'E-commerce',
  'Varejo/Comércio',
  'Financeiro',
  'Vendas',
  'Marketing',
  'Tecnologia',
  'Outros',
]

export const USE_CASES_MAP: Record<string, string[]> = {
  Medicina: [
    'Análise de exames e laudos',
    'Redação de prontuários',
    'Atendimento e triagem inicial',
    'Material educativo para pacientes',
    'Automação de whatsapp com IA',
    'Pesquisa científica e literatura',
    'Posologia e Receituário médico',
    'Criação de slides e apresentações',
  ],
  Saúde: [
    'Triagem e pré-diagnóstico',
    'Gestão de agendamentos ou escalas',
    'Suporte administrativo',
    'Educação de pacientes',
    'Análise de dados clínicos',
    'Comunicação com pacientes',
  ],
  'Construção/Engenharia': [
    'Renderização de projetos e plantas',
    'Análise de viabilidade técnica',
    'Orçamentos de compras e planilhas',
    'Gestão de projetos',
    'Relatórios técnicos',
    'Análise de documentação de obra',
    'Cálculos de base estrutural e demais cálculos',
  ],
  'E-commerce': [
    'Análise de campanhas de tráfego',
    'Atendimento ao cliente',
    'Descrição e título de produtos',
    'Gestão de inventário',
    'Criação de imagens com IA',
    'Pesquisa de fornecedores',
  ],
  'Varejo/Comércio': [
    'Atendimento ao cliente',
    'Análise de vendas',
    'Gestão de estoque',
    'Gestão de compras',
    'Criação de promoções',
    'Elaboração e melhoria de processos',
  ],
  Financeiro: [
    'Análise de resultados financeiros',
    'Elaboração de relatórios e pareceres contábeis',
    'Propostas e materiais educativos de investimento',
    'Estruturação de fluxo financeiro',
    'Criação de relatórios e dashboards',
    'Atendimento ao cliente',
  ],
  Vendas: [
    'Prospecção e qualificação de leads',
    'Pesquisa de prospects pré-reunião',
    'Argumentação de venda e quebra de objeções',
    'Follow-up com prospectos',
    'Estruturação de propostas',
    'Simulação de vendas com roleplay',
  ],
  Marketing: [
    'Criação de conteúdo para redes sociais',
    'Copywriting de anúncios',
    'Análise de campanhas e resultados',
    'Formulação de estratégias',
    'Análise de briefings',
    'Pesquisa de mercado e concorrentes',
  ],
  Tecnologia: [
    'Criação de documentos de requisitos (PRD)',
    'Desenvolvimento e revisão de código com IA',
    'Leitura e interpretação de documentações técnicas',
    'Configuração e parametrização de sistemas',
    'Pesquisa e análise de concorrentes e suas funcionalidades',
    'Criação e atualização de documentação interna',
    'Geração de casos de teste e QA',
    'Suporte técnico e resolução de chamados',
  ],
  Outros: [],
}

export const EMPLOYEE_COUNT_OPTIONS = [
  '1 a 10',
  '11 a 20',
  '21 a 50',
  '51 a 100',
  '101 a 500',
  'Acima de 500',
]

export const ROLE_OPTIONS = [
  'Empreendedor, Sócio ou CEO',
  'C-level, Diretor ou Head',
  'Gerente ou Coordenador',
  'Analista',
]
